"""add last_scanned_hash to scan_state

Revision ID: 220fb5c42944
Revises: 60d837f911b6
Create Date: 2026-08-07 21:52:55.401578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "220fb5c42944"
down_revision: Union[str, Sequence[str], None] = "60d837f911b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scan_state", sa.Column("last_scanned_hash", sa.String(length=66), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan_state", "last_scanned_hash")
    # ### end Alembic commands ###
