"""add transfer table

Revision ID: 603cb50d8357
Revises:
Create Date: 2026-08-04 23:02:34.382421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "603cb50d8357"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfer",
        sa.Column("tx_hash", sa.String(length=66), nullable=False),
        sa.Column("log_index", sa.Integer(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column("block_hash", sa.String(length=66), nullable=False),
        sa.Column("token", sa.String(length=10), nullable=False),
        sa.Column("from_address", sa.String(length=42), nullable=False),
        sa.Column("to_address", sa.String(length=42), nullable=False),
        sa.Column("value", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.PrimaryKeyConstraint("tx_hash", "log_index"),
    )
    op.create_index(op.f("ix_transfer_block_number"), "transfer", ["block_number"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transfer_block_number"), table_name="transfer")
    op.drop_table("transfer")
    # ### end Alembic commands ###
