"""add scanstate table

Revision ID: a05392bf6475
Revises: 603cb50d8357
Create Date: 2026-08-05 12:14:43.741408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a05392bf6475"
down_revision: Union[str, Sequence[str], None] = "603cb50d8357"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_state",
        sa.Column("token", sa.String(length=10), nullable=False),
        sa.Column("last_scanned_block", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scan_state")
    # ### end Alembic commands ###
