"""add token_threshold to subscriber

Revision ID: d0d88e857c4f
Revises: f8310197b57c
Create Date: 2026-08-22 13:20:21.500659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0d88e857c4f"
down_revision: Union[str, Sequence[str], None] = "f8310197b57c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriber",
        sa.Column(
            "token_threshold", sa.Integer(), server_default=sa.text("1000000"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriber", "token_threshold")
    # ### end Alembic commands ###
