"""add address_label table and corresponding enums

Revision ID: d11d2f99d4ec
Revises: 4e4454125547
Create Date: 2026-08-14 14:09:03.701966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d11d2f99d4ec"
down_revision: Union[str, Sequence[str], None] = "4e4454125547"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address_label",
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "exchange", "bridge", "treasury", "defi", "market_maker", name="address_category"
            ),
            nullable=False,
        ),
        sa.Column(
            "source", sa.Enum("verified", "inferred", "dune", name="address_source"), nullable=False
        ),
        sa.PrimaryKeyConstraint("address"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("address_label")
    sa.Enum(name="address_category").drop(op.get_bind())
    sa.Enum(name="address_source").drop(op.get_bind())
    # ### end Alembic commands ###
