"""add categories excluded to subscriber

Revision ID: f8310197b57c
Revises: d11d2f99d4ec
Create Date: 2026-08-18 19:00:16.853744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8310197b57c"
down_revision: Union[str, Sequence[str], None] = "d11d2f99d4ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriber",
        sa.Column(
            "from_categories_excluded",
            sa.ARRAY(
                sa.Enum(
                    "exchange",
                    "bridge",
                    "treasury",
                    "defi",
                    "market_maker",
                    name="address_category",
                )
            ),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "subscriber",
        sa.Column(
            "to_categories_excluded",
            sa.ARRAY(
                sa.Enum(
                    "exchange",
                    "bridge",
                    "treasury",
                    "defi",
                    "market_maker",
                    name="address_category",
                )
            ),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriber", "to_categories_excluded")
    op.drop_column("subscriber", "from_categories_excluded")
    # ### end Alembic commands ###
